const UI_TEXT = {
    es: {
        pageTitle: 'Prefijos telefónicos de Brasil',
        headerTitle: 'PREFIJOS TELEFÓNICOS DE BRASIL',
        headerSubtitle: 'Usa la rueda del ratón para hacer Zoom - Arrastra para mover el mapa',
        revealButton: 'REVELAR TODOS',
        resetButton: 'REINICIAR',
        gameModeBtn: 'MODO JUEGO',
        explorerModeBtn: 'SALIR DEL JUEGO',
        findDDD: 'Encuentra el prefijo:',
        diffTitle: 'SELECCIONA LA DIFICULTAD',
        btnEasy: 'FÁCIL (Por decena)',
        btnHard: 'DIFÍCIL (DDD exacto)',
        langButton: 'ENGLISH',
        counterLabel: 'Revelados:',
        fallbackRegion: 'Región',
        loadError: 'No se pudo cargar el mapa. Revisa la consola o tu conexión a internet.',
        loadErrorLog: 'Error al cargar el GeoJSON:'
    },
    en: {
        pageTitle: 'Area Codes in Brazil',
        headerTitle: 'AREA CODES IN BRAZIL',
        headerSubtitle: 'Use the mouse wheel to Zoom - Drag to move the map',
        revealButton: 'REVEAL ALL',
        resetButton: 'RESET',
        gameModeBtn: 'GAME MODE',
        explorerModeBtn: 'EXIT GAME',
        findDDD: 'Find the prefix:',
        diffTitle: 'SELECT DIFFICULTY',
        btnEasy: 'EASY (By decade)',
        btnHard: 'HARD (Exact DDD)',
        langButton: 'PORTUGUÊS',
        counterLabel: 'Revealed:',
        fallbackRegion: 'Region',
        loadError: 'Could not load the map. Check your console or internet connection.',
        loadErrorLog: 'Error loading GeoJSON:'
    },
    pt: {
        pageTitle: 'Códigos de Área do Brasil',
        headerTitle: 'CÓDIGOS DE ÁREA DO BRASIL',
        headerSubtitle: 'Use a roda do mouse para dar zoom · Arraste para mover o mapa',
        revealButton: 'REVELAR TODOS',
        resetButton: 'REINICIAR',
        gameModeBtn: 'MODO JOGO',
        explorerModeBtn: 'SAIR DO JOGO',
        findDDD: 'Encontre o prefixo:',
        diffTitle: 'SELECIONE A DIFICULDADE',
        btnEasy: 'FÁCIL (Por dezena)',
        btnHard: 'DIFÍCIL (DDD exato)',
        langButton: 'ESPAÑOL',
        counterLabel: 'Revelados:',
        fallbackRegion: 'Região',
        loadError: 'Não foi possível carregar o mapa. Verifique o console ou a sua conexão com a internet.',
        loadErrorLog: 'Erro ao carregar o GeoJSON:'
    }
};